# fly.toml app configuration file generated for dhdotcom on 2024-05-14T17:46:55-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dhrmx'
primary_region = 'ord'
kill_signal = "SIGINT"
kill_timeout = '5s'
restart_policy = "always"
swap_size = 1024


[experimental]
  auto_rollback = true

[[services]]
  internal_port = 3000
  protocol = "tcp"

    [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"


[[services.tcp_checks]]
    interval = "15s"
    timeout = "10s"
    grace_period = "5s"
    restart_limit = 0

 [[services.http_checks]]
    port = 3000
    "type" = "http"
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
    method = "GET"
    path = "/healthchecks"
    protocol = "http"
    tls_skip_verify = false

[env]
  FLY_SCALE_TO_ZERO = "1h"

[build]

[deploy]
  release_command = 'npx prisma db push && npx prisma migrate deploy'


[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

